### ISSUE TITLE
Mac 安装 Mongodb

### ISSUE THREAD

**Issue by laijbin** [laijbin/Blog#5]
[Install MongoDB on OS X](https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/)

里面提供了两种方法。一种是直接直接到[官网下载](https://www.mongodb.org/downloads?_ga=1.5541691.946515213.1446902555),但我怎么都下载不了。所以选择了第二种，[Homebrew](http://brew.sh/)。

安装Homebrew方法很简单，在终端里输入Homebrew官网里那句ruby命令即可。

安装完Homebrew后，输入`brew install mongodb`更新一下，然后输入`brew install mongodb`等待即可。

**Comment by laijbin** [comment]
用nodejs连接Mongodb时，报错：`Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)`

解决方法：command＋n打开新终端，输入`mongod --config /usr/local/etc/mongod.conf`把mongodb先启动起来，再在原来的启动即可。
